import { useLocation } from "wouter";
import { ArrowLeft } from "lucide-react";
import Footer from "@/components/Footer";

export default function Privacy() {
  const [, setLocation] = useLocation();

  return (
    <div className="min-h-screen bg-background text-foreground flex flex-col">
      <header className="p-6 border-b border-border flex items-center gap-4">
        <button
          onClick={() => window.history.length > 1 ? window.history.back() : setLocation("/home")}
          className="p-2 rounded-full hover:bg-secondary transition-colors"
          aria-label="Back"
        >
          <ArrowLeft size={20} />
        </button>
        <div>
          <div className="flex items-center gap-2">
            <img src="/logo.png" alt="" className="h-7 w-auto" />
            <span className="text-lg font-bold text-primary">Prolorg</span>
          </div>
          <p className="text-[10px] text-muted-foreground leading-none mt-0.5">The Talent stage app</p>
        </div>
      </header>

      <main className="flex-1 w-full md:w-4/5 lg:w-3/5 mx-auto px-6 py-12">
        <h1 className="text-4xl font-bold mb-2">Privacy Policy</h1>
        <p className="text-xs text-muted-foreground mb-10">Last updated: May 2026</p>

        <div className="space-y-8 text-sm text-muted-foreground leading-relaxed">
          <section>
            <h2 className="text-base font-bold text-foreground mb-2">1. Who We Are</h2>
            <p>Prolorg is operated by Cryp Tok Solutions ("we", "us", "our"). This Privacy Policy explains what personal data we collect, how we use it, and your rights in relation to it.</p>
          </section>

          <section>
            <h2 className="text-base font-bold text-foreground mb-2">2. Information We Collect</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li><span className="text-foreground font-medium">Account information</span> — your name, email address, and password (stored as a secure hash) when you sign up.</li>
              <li><span className="text-foreground font-medium">Profile information</span> — stage name, city, country, bio, keywords, availability, and any social/professional links you choose to add.</li>
              <li><span className="text-foreground font-medium">Video content</span> — the 60-second prologue you record and upload to the Platform.</li>
              <li><span className="text-foreground font-medium">Psychometric answers</span> — your responses to the Real Talk scenario questions.</li>
              <li><span className="text-foreground font-medium">Usage data</span> — session information, pages visited, and interactions with the feed (e.g. saves) to operate the service.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-bold text-foreground mb-2">3. How We Use Your Information</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>To create and manage your account.</li>
              <li>To display your profile and prologue to companies, investors, and co-founders browsing the feed.</li>
              <li>To enable search and discovery features.</li>
              <li>To maintain platform security and enforce our Terms of Use.</li>
              <li>To improve the Platform based on aggregate usage patterns.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-bold text-foreground mb-2">4. Who Can See Your Data</h2>
            <p>Your profile, prologue video, and psychometric answers are visible to anyone who accesses the Platform (including guests who have not registered). Your email address and password hash are never shared publicly. Links you add to your profile (LinkedIn, GitHub, X, etc.) are displayed as-is and will direct visitors to those external platforms.</p>
          </section>

          <section>
            <h2 className="text-base font-bold text-foreground mb-2">5. Data Storage & Security</h2>
            <p>Your data is stored on secure servers managed by Replit Infrastructure and Google Cloud Storage. Videos are stored as private objects accessible only via time-limited signed URLs generated by our server. We apply industry-standard security practices, but no system is completely immune to risk.</p>
          </section>

          <section>
            <h2 className="text-base font-bold text-foreground mb-2">6. Cookies & Sessions</h2>
            <p>We use secure, HTTP-only session cookies to keep you logged in. These are stored in a PostgreSQL session store and expire after inactivity. We do not use third-party advertising cookies.</p>
          </section>

          <section>
            <h2 className="text-base font-bold text-foreground mb-2">7. Your Rights</h2>
            <p className="mb-2">You have the right to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Access the personal data we hold about you.</li>
              <li>Request correction of inaccurate data via your profile settings.</li>
              <li>Request deletion of your account and associated data by contacting us.</li>
              <li>Withdraw consent at any time by deleting your account.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-bold text-foreground mb-2">8. Third-Party Services</h2>
            <p>We use Clerk for authentication (subject to <a href="https://clerk.com/privacy" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">Clerk's Privacy Policy</a>) and Google Cloud Storage for video hosting. We do not sell your data to any third party.</p>
          </section>

          <section>
            <h2 className="text-base font-bold text-foreground mb-2">9. Changes to This Policy</h2>
            <p>We may update this Privacy Policy from time to time. We will notify users of material changes by updating the "last updated" date above. Continued use of the Platform constitutes acceptance of the revised policy.</p>
          </section>

          <section>
            <h2 className="text-base font-bold text-foreground mb-2">10. Contact</h2>
            <p>Privacy questions or deletion requests? Contact us at <a href="https://cryptok.online" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">cryptok.online</a> or via the <button onClick={() => setLocation("/report-issue")} className="text-primary hover:underline">feedback form</button>.</p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
